### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by awab228** [MofadalAltyeb/MTKAuthBypassQT#1]
Hello , 
building for Mingw 5.14.2 64bit results in this this error 

C:\Users\****\MTKAuthBypassQT-main\brom\boot_rom.cpp:262: error: cast from 'WinUSB::usb_dev_handle*' to 'quint {aka unsigned int}' loses precision [-fpermissive]
..\MTKAuthBypassQT-main\brom\boot_rom.cpp: In member function 'qbool boot_rom::UsbSendDevCtrl(qchar, qchar, qshort, qshort, qbyte&)':
..\MTKAuthBypassQT-main\brom\boot_rom.cpp:262:131: error: cast from 'WinUSB::usb_dev_handle*' to 'quint {aka unsigned int}' loses precision [-fpermissive]
                     qInfo().noquote().nospace() << qstr("MTKCommIO::UsbSendDevCtrl(usb_open:%0:%1)").arg(mCallback::GetU32((quint)hnd), usb_strerror());
                                                                                                                                   ^~~

**Comment by mfdl** [comment]
You can add manually/force casting :
static_cast<uint32_t> . 
or comment it out, it's only used for log debugging inside the IDE.

**Comment by awab228** [comment]
after commenting it out , new error , 

C:\Users\**\MTKAuthBypassQT-main\comport\usbdevfinder.cpp:87: error: invalid conversion from 'HRESULT (*)(HWND, UINT, WPARAM, LPARAM) {aka long int (*)(HWND__*, unsigned int, long long unsigned int, long long int)}' to 'WNDPROC {aka long long int (*)(HWND__*, unsigned int, long long unsigned int, long long int)}' [-fpermissive]
..\MTKAuthBypassQT-main\comport\usbdevfinder.cpp: In member function 'ATOM USBCore::USBFinder::RegisterWindowClass(USBCore::USBDevInfo&)':
..\MTKAuthBypassQT-main\comport\usbdevfinder.cpp:87:24: error: invalid conversion from 'HRESULT (*)(HWND, UINT, WPARAM, LPARAM) {aka long int (*)(HWND__*, unsigned int, long long unsigned int, long long int)}' to 'WNDPROC {aka long long int (*)(HWND__*, unsigned int, long long unsigned int, long long int)}' [-fpermissive]
     wcex.lpfnWndProc = &USBFinder::WndProc;
                        ^~~~~~~~~~

**Comment by awab228** [comment]
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lfontconfig
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lfreetype
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ljpeg
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ltiff
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lwebp
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lwebpdemux
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lwebpmux
D:/Qt/Qt5.14.2/Tools/mingw730_32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lpng16
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:174: output/MTKAuthBypassQT.exe] Error 1
12:22:01: The process "D:\Qt\Qt5.14.2\Tools\mingw730_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project MTKAuthBypassQT (kit: static mingw runtime)
When executing step "Make"

I am getting this strange error at the last linking process , can you guess what's missing ?
