### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by kashifbharwana** [MofadalAltyeb/MTKAuthBypassQT#5]
C:\Users\kashif bharwana\Downloads\Compressed\MTKAuthBypassQT-main\MTKAuthBypassQT-main\brom\com_io.cpp:289: error: undefined reference to `_imp__ntohl@4'
ProjectTemp/debug/.obj/com_io.o: In function `ZN8boot_rom6read32EPj':
C:\Users\kashif bharwana\Downloads\Compressed\MTKAuthBypassQT-main\build-MTKAuthBypassQT-Desktop_Qt_5_14_2_MinGW_32_bit-Debug/../MTKAuthBypassQT-main/brom/com_io.cpp:289: undefined reference to `_imp__ntohl@4'

**Comment by kashifbharwana** [comment]
ProjectTemp/release/.obj/com_io.o:com_io.cpp:(.text+0x159a): undefined reference to `_imp__ntohs@4'

**Comment by itafaqahmed** [comment]
l

**Comment by mfdl** [comment]
please use QT 5.14.2 MinGW 32bit Static version.

**Comment by kashifbharwana** [comment]
main\build-MTKAuthBypassQT-Desktop_Qt_5_14_2_MinGW_32_bit-Debug\output\MTKAuthBypassQT.exe" is missing, or you may have insufficient permissions to invoke the program.

**Comment by itafaqahmed** [comment]
Problem solved Thanks 👍

**Comment by itafaqahmed** [comment]
Problem solved
